"""Legal / illegal zones.

Real data (put in data/raw/):
  wdpa/      WDPA polygons for India (shapefile or GeoJSON) from protectedplanet.net
  osm/       Geofabrik India shapefile layer gis_osm_landuse_a_free_1.shp
             (features with fclass 'forest' or 'nature_reserve' become reserved forest)
Without them, data/samples/zones_sample.geojson is used. Licensed blocks are
always generated by the seed script (they're sample data).
"""
import json

from app.config import RAW_DIR, SAMPLES_DIR
from .common import geojson_polygons, in_region, shapefile_polygons, simplify_ring


def _ring_in_region(ring):
    return any(in_region(lat, lon) for lat, lon in ring[:: max(1, len(ring) // 20)])


def _from_shapefiles(folder, name_keys, keep=lambda rec: True, zone_type="protected_area", source=""):
    import shapefile
    out = []
    for shp in sorted(folder.glob("*.shp")):
        reader = shapefile.Reader(str(shp))
        names = [f[0] for f in reader.fields[1:]]
        for sr in reader.iterShapeRecords():
            rec = dict(zip(names, sr.record))
            if not keep(rec):
                continue
            name = next((str(rec[k]) for k in name_keys if rec.get(k)), zone_type)
            for ring in shapefile_polygons(sr.shape):
                if _ring_in_region(ring):
                    out.append(dict(name=name, zone_type=zone_type, legal_to_drill=False, authority=rec.get("MANG_AUTH"),
                                    polygon=simplify_ring(ring), source=f"{source} ({shp.name})"))
    return out


def load_zones() -> tuple[list[dict], str]:
    zones, used = [], []
    wdpa = RAW_DIR / "wdpa"
    if wdpa.exists():
        zones += _from_shapefiles(wdpa, ["NAME", "ORIG_NAME"], zone_type="protected_area", source="WDPA")
        for gj in wdpa.glob("*.geojson"):
            for f in json.loads(gj.read_text())["features"]:
                for ring in geojson_polygons(f):
                    if _ring_in_region(ring):
                        zones.append(dict(name=f["properties"].get("NAME", "Protected area"), zone_type="protected_area",
                                          legal_to_drill=False, polygon=simplify_ring(ring), source="WDPA"))
        used.append("WDPA")
    osm = RAW_DIR / "osm"
    if osm.exists():
        zones += _from_shapefiles(osm, ["name"], keep=lambda r: r.get("fclass") in ("forest", "nature_reserve"),
                                  zone_type="reserved_forest", source="OpenStreetMap / Geofabrik")
        used.append("OSM")
    if zones:
        return zones, " + ".join(used)
    data = json.loads((SAMPLES_DIR / "zones_sample.geojson").read_text())
    for f in data["features"]:
        p = f["properties"]
        for ring in geojson_polygons(f):
            zones.append(dict(name=p["name"], zone_type=p["zone_type"], legal_to_drill=p["legal_to_drill"],
                              authority=p.get("authority"), polygon=ring, source=p.get("source", "Sample")))
    return zones, "Sample zones (simplified outlines of real protected areas)"
